# Generated by Django 3.2.3 on 2021-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_extenduser_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='otp',
            field=models.CharField(default='', max_length=4),
        ),
    ]
