# Generated by Django 3.2.3 on 2021-07-16 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polling', '0008_alter_extenduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='aadhar',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='voterid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='ward',
            field=models.CharField(default='', max_length=10),
        ),
    ]
