# Generated by Django 3.2 on 2022-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0011_extenduser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
