# Generated by Django 3.2 on 2022-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0012_alter_extenduser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
    ]
