# Generated by Django 3.2 on 2022-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0016_extenduser_aadharphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='aadharphoto',
            field=models.FileField(default=False, upload_to='images/'),
        ),
    ]
