# Generated by Django 3.2 on 2022-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0018_auto_20220522_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='profile',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
