# Generated by Django 3.2 on 2022-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0019_alter_aadhar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='profile',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
