# Generated by Django 3.2 on 2022-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0020_alter_aadhar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
