# Generated by Django 3.2 on 2022-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0021_aadhar_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
