# Generated by Django 3.2 on 2022-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0024_alter_aadhar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='profile',
            field=models.FileField(default=False, upload_to='media/'),
        ),
    ]
